services:
  mysql:
    image: mysql:8.4
    container_name: iee-portal-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iee_portal
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - iee_portal_mysql:/var/lib/mysql

volumes:
  iee_portal_mysql:
